name: imagenet21k
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.8
  
  # Core PyTorch and CUDA
  - pytorch=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=11.0
  
  # Core scientific computing
  - numpy
  - scipy
  
  # Image processing
  - pillow
  - opencv
  
  # Visualization and monitoring
  - matplotlib
  
  # Development tools
  - pip
  
  # Pip-only packages
  - pip:
      # PyTorch image models (timm)
      - git+https://github.com/rwightman/pytorch-image-models.git
      
      # Inplace ABN for TResNet
      - git+https://github.com/mapillary/inplace_abn.git@v1.0.12
      
      # Data augmentation
      - randaugment
      
      # Experiment tracking
      - wandb
      
      # Utilities
      - tqdm
